### ISSUE TITLE
pybedtools Error

### ISSUE THREAD

**Issue by lmanchon** [dariober/genomeGraphs#1]
--Hi,

running this command on a well coordinate sorted bam file:
genomeGraphs -i LIB.bam -b Homo_sapiens_GRCh38.gtf -f Homo_sapiens_GRCh38.fa -o  LIB

it fails with this error message:

Traceback (most recent call last):
  File "/save/lmanchon/GENOMEGRAPH/bin/genomeGraphs", line 5, in <module>
    genomeGraphs.main()
  File "/save/lmanchon/GENOMEGRAPH/lib/python/genome_graphs/genomeGraphs.py", line 480, in main
    xinbed= pybedtools.BedTool(inbed).each(pycoverage.slopbed, slop).merge().saveas()
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/site-packages/pybedtools/bedtool.py", line 650, in decorated
    result = method(self, _args, *_kwargs)
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/site-packages/pybedtools/bedtool.py", line 230, in wrapped
    check_stderr=check_stderr)
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/site-packages/pybedtools/helpers.py", line 422, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

```
    bedtools merge -i stdin
```

Error message was:
Error: Sorted input specified, but the file stdin has the following out of order record
1       havana  exon    12608   12726   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "2"; gene_name "DDX11L1"; gen
e_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; havana_gene "OTTHUMG00000000961"; havana_gene_version "2"; transcript_name "DDX11L1-002"; transcript_source "havana"; transcript_biotype
"processed_transcript"; havana_transcript "OTTHUMT00000362751"; havana_transcript_version "1"; exon_id "ENSE00003582793"; exon_version "1"; tag "basic"; transcript_support_level "1";

i don't know what happens here, is there something to patch ?

thank you --

**Comment by dariober** [comment]
Hi- Sorry about that and thanks for reporting the issue. I should have fixed it now. Can you try to download and re-install the package again?

By the way, Homo_sapiens_GRCh38.gtf is that the whole annotation file for GRCh38? If so, it will take a long time to plot each interval!

**Comment by lmanchon** [comment]
Le 16/02/2016 16:22, Dario Beraldi a écrit :

> Hi- Sorry about that and thanks for reporting the issue. I should have 
> fixed it now. Can you try to download and re-install the package again?
> 
> By the way, Homo_sapiens_GRCh38.gtf is that the whole annotation file 
> for GRCh38? If so, it will take a long time to plot each interval!

yes i know.

i think i have identified the problem, my version of bedtools is v2.22.1
and in the last version 2.25.0 a bug that caused incorrect reporting of 
/overlap/ for zero-length BED have been fixed.

> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dariober/genomeGraphs/issues/1#issuecomment-184726989.

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by dariober** [comment]
What I did was changing:
xinbed= pybedtools.BedTool(inbed).each(pycoverage.slopbed, slop).merge().saveas()
to
xinbed= pybedtools.BedTool(inbed).each(pycoverage.slopbed, slop).sort().merge().saveas()

So resorting the input to merge even if it should be already sorted.

Let me know if you are still having issues...

**Comment by lmanchon** [comment]
Le 16/02/2016 17:54, Dario Beraldi a écrit :

> What I did was changing:
> xinbed= pybedtools.BedTool(inbed).each(pycoverage.slopbed, 
> slop).merge().saveas()
> to
> xinbed= pybedtools.BedTool(inbed).each(pycoverage.slopbed, 
> slop).sort().merge().saveas()
> 
> So resorting the input to merge even if it should be already sorted.
> 
> Let me know if you are still having issues...

ok problem is over,
that's work fine now.
And i confirm it's very slow for human genome (big gtf)

thank you so much for updated the code.

Laurent --
